# Generated by Django 6.0.2 on 2026-03-31 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Дом', max_length=50)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=20)),
                ('corpus', models.CharField(blank=True, max_length=20)),
                ('entrance', models.CharField(blank=True, max_length=10)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('flat', models.CharField(blank=True, max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
