// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu11_sykqlpngV0o4KZ5kH6PL5g3ZxAqE',
    appId: '1:711483695169:web:8140a0cda9b92cc0d3a6c0',
    messagingSenderId: '711483695169',
    projectId: 'delivery-app-cameback-20-fbcfe',
    authDomain: 'delivery-app-cameback-20-fbcfe.firebaseapp.com',
    storageBucket: 'delivery-app-cameback-20-fbcfe.firebasestorage.app',
    measurementId: 'G-VCC7EGGP7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADIP7kPEfeKcCT8Hso9UjLyhezPZGZIuY',
    appId: '1:711483695169:android:179a60c430311ad0d3a6c0',
    messagingSenderId: '711483695169',
    projectId: 'delivery-app-cameback-20-fbcfe',
    storageBucket: 'delivery-app-cameback-20-fbcfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmnQh4Er5HyVTkjEvWpzeOzFLZQqTSbJM',
    appId: '1:711483695169:ios:0df0a1a4e5e2fb7ad3a6c0',
    messagingSenderId: '711483695169',
    projectId: 'delivery-app-cameback-20-fbcfe',
    storageBucket: 'delivery-app-cameback-20-fbcfe.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmnQh4Er5HyVTkjEvWpzeOzFLZQqTSbJM',
    appId: '1:711483695169:ios:0df0a1a4e5e2fb7ad3a6c0',
    messagingSenderId: '711483695169',
    projectId: 'delivery-app-cameback-20-fbcfe',
    storageBucket: 'delivery-app-cameback-20-fbcfe.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu11_sykqlpngV0o4KZ5kH6PL5g3ZxAqE',
    appId: '1:711483695169:web:73fd2b6ba8103d05d3a6c0',
    messagingSenderId: '711483695169',
    projectId: 'delivery-app-cameback-20-fbcfe',
    authDomain: 'delivery-app-cameback-20-fbcfe.firebaseapp.com',
    storageBucket: 'delivery-app-cameback-20-fbcfe.firebasestorage.app',
    measurementId: 'G-0SQP1QH24Z',
  );
}
